# Generated by Django 5.2.8 on 2025-11-24 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('cliente', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('andamento', 'Em andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('participantes', models.ManyToManyField(related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('lider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lidera_equipe', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(related_name='equipes', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='core.projeto')),
            ],
        ),
    ]
